# Generated by Django 2.0.3 on 2018-03-29 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yellowant_user_id', models.IntegerField()),
                ('yellowant_team_subdomain', models.CharField(max_length=256)),
                ('yellowant_integration_id', models.IntegerField(unique=True)),
                ('yellowant_integration_invoke_name', models.CharField(max_length=256)),
                ('yellowant_integration_token', models.CharField(max_length=2048)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
